import type { ScoreRule } from './types';

export const INITIAL_RULES: ScoreRule[] = [
  {
    id: 'rule-27',
    version: 3,
    term: 27,
    name: '27기 정규 출결 점수 규칙',
    startDate: '2026-07-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
    activatedAt: '2026-07-01',
    createdBy: '27기 대표진',
    description: '27기 하계 방학 세션 및 2학기 정규활동/스터디 출결 배점 규정',
    present: 0,
    late: -1,
    absent: -3,
    absentPenalty: -3,
    unexcusedAbsentPenalty: -4,
    latePenalty: -1,
    earlyLeavePenalty: -1,
    unexcusedLatePenalty: -4,
    presentScore: 0,
    studyFailPenalty: -5,
    studyPerfectBonus: 3,
    studyPassBonus: 1,
    studyLeaderBonus: 1,
  },
  {
    id: 'rule-26',
    version: 2,
    term: 26,
    name: '26기 정규 출결 점수 규칙',
    startDate: '2026-01-01',
    endDate: '2026-06-30',
    status: 'INACTIVE',
    activatedAt: '2026-01-01',
    createdBy: '26기 대표진',
    description: '26기 동계 방학 및 1학기 출결 배점 규정 (과거 이력 보존)',
    present: 0,
    late: -1,
    absent: -3,
    absentPenalty: -3,
    unexcusedAbsentPenalty: -4,
    latePenalty: -1,
    earlyLeavePenalty: -1,
    unexcusedLatePenalty: -4,
    presentScore: 0,
    studyFailPenalty: -5,
    studyPerfectBonus: 3,
    studyPassBonus: 1,
    studyLeaderBonus: 1,
  },
  {
    id: 'rule-25',
    version: 1,
    term: 25,
    name: '25기 정규 출결 점수 규칙',
    startDate: '2025-07-01',
    endDate: '2025-12-31',
    status: 'INACTIVE',
    activatedAt: '2025-07-01',
    createdBy: '25기 대표진',
    description: '25기 하계 방학 및 2학기 출결 배점 규정 (과거 이력 보존)',
    present: 0,
    late: -0.5,
    absent: -2,
    absentPenalty: -2,
    unexcusedAbsentPenalty: -3,
    latePenalty: -0.5,
    earlyLeavePenalty: -0.5,
    unexcusedLatePenalty: -3,
    presentScore: 0,
    studyFailPenalty: -4,
    studyPerfectBonus: 2,
    studyPassBonus: 1,
    studyLeaderBonus: 1,
  },
];
