import type { ActivePage } from "./activePage";

export const PAGE_LABELS: Record<ActivePage, string> = {
  "content-archive": "아카이빙 (프로젝트·블로그·사진)",
  "content-faq": "자주 묻는 질문 (FAQ)",
  "content-curriculum": "커리큘럼 관리",
  "content-reviews": "수료자 후기 관리",
  content: "콘텐츠 관리",
  recruiting: "모집 공고 관리",
  "recruiting-posts": "모집 공고 관리",
  "recruiting-questions": "지원서 문항 설정",
  "recruiting-preview": "지원자 화면 미리보기",
  "recruiting-csv": "지원서 CSV 추출",
  "recruiting-leads": "사전 알림 명단",
  evaluation: "서류 평가 대시보드",
  "evaluation-evals": "서류 평가 대시보드 (SUBMITTED)",
  "evaluation-applicants": "전체 지원자 현황 (DRAFT 포함)",
  "evaluation-promote": "최종 합불 & 정회원 승격",
  "att-session": "BASE Term 출결 관리",
  "att-adv": "ADV Term 출결 관리",
  "att-events": "행사 출결 관리",
  "att-study": "스터디 출결 관리",
  "att-input-adv": "ADV 출결 입력 및 증빙 (팀장용)",
  "att-input-study": "스터디 출결 입력 및 증빙 (팀장용)",
  "att-input": "출결 입력 및 증빙 등록 (팀장용)",
  "att-hosts": "HOST 계정·팀 연결 (ID/PW 발급)",
  "att-scores": "출결 점수 집계",
  "att-rules": "점수 규칙",
  "att-dashboard": "출결 대시보드 & 인증 검토",
  "att-internal": "정규 출결 관리",
  system: "시스템·계정",
  "system-accounts": "운영진 계정 관리 (CRUD)",
  "system-permissions": "권한 매트릭스 (10대 Permission)",
  "system-audit": "보안 감사 로그",
};
