import type { Member, StudyTeamInfo } from "./types";

export const INITIAL_STUDY_TEAMS: StudyTeamInfo[] = [
  {
    id: "st_a",
    teamName: "A팀",
    studyName: "머신러닝 & 딥러닝 실전 스터디",
    leaderName: "이민준",
    category: "데이터 분석",
    schedule: "매주 화요일 19:00",
    studyType: "방학 스터디",
    description: "논문 리딩 및 캐글 경진대회 베이스라인 구축",
    createdAt: "2025-02-28",
  },
  {
    id: "st_b",
    teamName: "B팀",
    studyName: "대용량 분산 데이터 파이프라인",
    leaderName: "강태양",
    category: "데이터 엔지니어링",
    schedule: "매주 목요일 19:30",
    studyType: "방학 스터디",
    description: "Kafka, Spark, Airflow 기반 실시간 ETL 구축",
    createdAt: "2025-02-28",
  },
  {
    id: "st_c",
    teamName: "C팀",
    studyName: "Tableau & D3.js 대시보드 시각화",
    leaderName: "문지훈",
    category: "데이터 시각화",
    schedule: "매주 수요일 20:00",
    studyType: "학기 스터디",
    description: "인터랙티브 웹 시각화 및 스토리텔링 대시보드",
    createdAt: "2025-02-28",
  },
  {
    id: "st_d",
    teamName: "D팀",
    studyName: "LLM Agent & RAG 시스템 구현",
    leaderName: "고준서",
    category: "생성형 AI",
    schedule: "매주 토요일 14:00",
    studyType: "학기 스터디",
    description: "LangChain, LlamaIndex 기반 프로덕션 RAG",
    createdAt: "2025-02-28",
  },
];

export const ACTIVITIES = [
  { id: "study", name: "스터디", color: "#3b82f6", bg: "rgba(59,130,246,0.12)" },
];

export const MEMBERS: Record<string, Member[]> = {
  A팀: [
    { id: "a1", name: "이민준", year: "21", track: "분석" },
    { id: "a2", name: "박서연", year: "22", track: "분석" },
    { id: "a3", name: "김도현", year: "21", track: "엔지니어링" },
    { id: "a4", name: "최지우", year: "23", track: "시각화" },
    { id: "a5", name: "정하은", year: "22", track: "분석" },
    { id: "a6", name: "오승현", year: "21", track: "엔지니어링" },
    { id: "a7", name: "한예린", year: "23", track: "시각화" },
    { id: "a8", name: "윤재혁", year: "22", track: "분석" },
  ],
  B팀: [
    { id: "b1", name: "강태양", year: "21", track: "엔지니어링" },
    { id: "b2", name: "임수진", year: "22", track: "엔지니어링" },
    { id: "b3", name: "류현우", year: "23", track: "분석" },
    { id: "b4", name: "신아름", year: "21", track: "엔지니어링" },
    { id: "b5", name: "백민혁", year: "22", track: "시각화" },
    { id: "b6", name: "장나연", year: "23", track: "엔지니어링" },
    { id: "b7", name: "조영준", year: "21", track: "분석" },
    { id: "b8", name: "허채원", year: "22", track: "엔지니어링" },
  ],
  C팀: [
    { id: "c1", name: "문지훈", year: "21", track: "시각화" },
    { id: "c2", name: "노유진", year: "22", track: "시각화" },
    { id: "c3", name: "원승민", year: "23", track: "분석" },
    { id: "c4", name: "송하늘", year: "22", track: "시각화" },
    { id: "c5", name: "양도연", year: "21", track: "엔지니어링" },
    { id: "c6", name: "진서영", year: "23", track: "시각화" },
    { id: "c7", name: "표건우", year: "22", track: "분석" },
    { id: "c8", name: "홍미래", year: "21", track: "시각화" },
  ],
  D팀: [
    { id: "d1", name: "고준서", year: "22", track: "분석" },
    { id: "d2", name: "남소희", year: "23", track: "엔지니어링" },
    { id: "d3", name: "도현진", year: "21", track: "분석" },
    { id: "d4", name: "마지원", year: "22", track: "시각화" },
    { id: "d5", name: "배수현", year: "23", track: "엔지니어링" },
    { id: "d6", name: "서태준", year: "21", track: "분석" },
    { id: "d7", name: "안예은", year: "22", track: "시각화" },
    { id: "d8", name: "차민규", year: "23", track: "분석" },
  ],
};

export const ADV_INITIAL_TEAMS: StudyTeamInfo[] = [
  {
    id: "adv_t1",
    teamName: "분석 1팀",
    studyName: "LLM Agentic 워크플로우",
    leaderName: "고준서",
    category: "분석",
    schedule: "매주 화요일 19:00",
    studyType: "방학 스터디",
    description: "LangGraph 기반 다중 에이전트 협업 시스템 구축",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t2",
    teamName: "분석 2팀",
    studyName: "시계열 예측 솔루션",
    leaderName: "김서하",
    category: "분석",
    schedule: "매주 수요일 19:00",
    studyType: "방학 스터디",
    description: "금융 및 이상탐지 시계열 파운데이션 모델링",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t3",
    teamName: "분석 3팀",
    studyName: "금융 FDS 이상거래 탐지 AI",
    leaderName: "박성준",
    category: "분석",
    schedule: "매주 목요일 19:00",
    studyType: "방학 스터디",
    description: "그래프 신경망 기반 금융 사기 및 이상 거래 실시간 탐지",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t4",
    teamName: "시각화 1팀",
    studyName: "인터랙티브 웹 시각화 대시보드",
    leaderName: "최민혁",
    category: "시각화",
    schedule: "매주 수요일 20:00",
    studyType: "방학 스터디",
    description: "Next.js & D3.js 기반 엔터프라이즈 데이터 시각화",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t5",
    teamName: "시각화 2팀",
    studyName: "지리공간 맵핑 & 인포그래픽",
    leaderName: "문지훈",
    category: "시각화",
    schedule: "매주 목요일 20:00",
    studyType: "방학 스터디",
    description: "Mapbox & Deck.gl 기반 공간 데이터 시각화",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t6",
    teamName: "시각화 3팀",
    studyName: "3D 바이오 메디컬 시각화",
    leaderName: "한예린",
    category: "시각화",
    schedule: "매주 금요일 20:00",
    studyType: "방학 스터디",
    description: "Three.js 기반 인체 장기 3D 렌더링 및 헬스케어 차트",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t7",
    teamName: "엔지 1팀",
    studyName: "실시간 분산 스트리밍 추천",
    leaderName: "강태양",
    category: "엔지니어링",
    schedule: "매주 목요일 19:30",
    studyType: "방학 스터디",
    description: "Kafka & Redis 기반 초개인화 실시간 추천 엔진",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t8",
    teamName: "엔지 2팀",
    studyName: "멀티모달 헬스케어 AI 솔루션",
    leaderName: "이도현",
    category: "엔지니어링",
    schedule: "매주 금요일 19:30",
    studyType: "방학 스터디",
    description: "의료 영상 및 EMR 텍스트 통합 분석 솔루션",
    createdAt: "2026-08-15",
  },
  {
    id: "adv_t9",
    teamName: "엔지 3팀",
    studyName: "엔터프라이즈 RAG MLOps 파이프라인",
    leaderName: "백민혁",
    category: "엔지니어링",
    schedule: "매주 토요일 14:00",
    studyType: "방학 스터디",
    description: "vLLM 및 Ray 기반 고성능 분산 서빙 인프라 구축",
    createdAt: "2026-08-15",
  },
];

export const ADV_MEMBERS: Record<string, Member[]> = {
  "분석 1팀": [
    { id: "adv_1_1", name: "고준서", year: "27", track: "분석" },
    { id: "adv_1_2", name: "김서하", year: "28", track: "분석" },
    { id: "adv_1_3", name: "이민준", year: "28", track: "분석" },
    { id: "adv_1_4", name: "정채원", year: "28", track: "분석" },
  ],
  "분석 2팀": [
    { id: "adv_2_1", name: "박지훈", year: "28", track: "분석" },
    { id: "adv_2_2", name: "오승현", year: "28", track: "분석" },
    { id: "adv_2_3", name: "도현진", year: "27", track: "분석" },
    { id: "adv_2_4", name: "마지원", year: "28", track: "분석" },
  ],
  "분석 3팀": [
    { id: "adv_3_1", name: "박성준", year: "27", track: "분석" },
    { id: "adv_3_2", name: "신유진", year: "28", track: "분석" },
    { id: "adv_3_3", name: "안서연", year: "28", track: "분석" },
    { id: "adv_3_4", name: "조민규", year: "28", track: "분석" },
  ],
  "시각화 1팀": [
    { id: "adv_4_1", name: "최민혁", year: "28", track: "시각화" },
    { id: "adv_4_2", name: "한예린", year: "28", track: "시각화" },
    { id: "adv_4_3", name: "문지훈", year: "27", track: "시각화" },
    { id: "adv_4_4", name: "장나연", year: "28", track: "시각화" },
  ],
  "시각화 2팀": [
    { id: "adv_5_1", name: "윤재혁", year: "28", track: "시각화" },
    { id: "adv_5_2", name: "송하늘", year: "27", track: "시각화" },
    { id: "adv_5_3", name: "노유진", year: "27", track: "시각화" },
    { id: "adv_5_4", name: "원승민", year: "28", track: "시각화" },
  ],
  "시각화 3팀": [
    { id: "adv_6_1", name: "배준호", year: "28", track: "시각화" },
    { id: "adv_6_2", name: "권나현", year: "28", track: "시각화" },
    { id: "adv_6_3", name: "서진우", year: "27", track: "시각화" },
    { id: "adv_6_4", name: "하예원", year: "28", track: "시각화" },
  ],
  "엔지 1팀": [
    { id: "adv_7_1", name: "강태양", year: "28", track: "엔지니어링" },
    { id: "adv_7_2", name: "이도현", year: "28", track: "엔지니어링" },
    { id: "adv_7_3", name: "임수진", year: "28", track: "엔지니어링" },
    { id: "adv_7_4", name: "남소희", year: "27", track: "엔지니어링" },
  ],
  "엔지 2팀": [
    { id: "adv_8_1", name: "박성훈", year: "28", track: "엔지니어링" },
    { id: "adv_8_2", name: "백민혁", year: "28", track: "엔지니어링" },
    { id: "adv_8_3", name: "류현우", year: "28", track: "엔지니어링" },
    { id: "adv_8_4", name: "조영준", year: "28", track: "엔지니어링" },
  ],
  "엔지 3팀": [
    { id: "adv_9_1", name: "황지수", year: "28", track: "엔지니어링" },
    { id: "adv_9_2", name: "김민재", year: "28", track: "엔지니어링" },
    { id: "adv_9_3", name: "이지호", year: "27", track: "엔지니어링" },
    { id: "adv_9_4", name: "최현우", year: "28", track: "엔지니어링" },
  ],
};
