import type { Member, StudyTeamInfo } from "./types";

export const INITIAL_STUDY_TEAMS: StudyTeamInfo[] = [
  {
    id: "st_a",
    teamName: "A팀",
    studyName: "머신러닝 & 딥러닝 실전 스터디",
    leaderName: "이민준",
    category: "데이터 분석",
    schedule: "매주 화요일 19:00",
    studyType: "방학 스터디",
    description: "논문 리딩 및 캐글 경진대회 베이스라인 구축",
    createdAt: "2025-02-28",
  },
  {
    id: "st_b",
    teamName: "B팀",
    studyName: "대용량 분산 데이터 파이프라인",
    leaderName: "강태양",
    category: "데이터 엔지니어링",
    schedule: "매주 목요일 19:30",
    studyType: "방학 스터디",
    description: "Kafka, Spark, Airflow 기반 실시간 ETL 구축",
    createdAt: "2025-02-28",
  },
  {
    id: "st_c",
    teamName: "C팀",
    studyName: "Tableau & D3.js 대시보드 시각화",
    leaderName: "문지훈",
    category: "데이터 시각화",
    schedule: "매주 수요일 20:00",
    studyType: "학기 스터디",
    description: "인터랙티브 웹 시각화 및 스토리텔링 대시보드",
    createdAt: "2025-02-28",
  },
  {
    id: "st_d",
    teamName: "D팀",
    studyName: "LLM Agent & RAG 시스템 구현",
    leaderName: "고준서",
    category: "생성형 AI",
    schedule: "매주 토요일 14:00",
    studyType: "학기 스터디",
    description: "LangChain, LlamaIndex 기반 프로덕션 RAG",
    createdAt: "2025-02-28",
  },
];

export const ACTIVITIES = [
  { id: "study", name: "스터디", color: "#3b82f6", bg: "rgba(59,130,246,0.12)" },
];

export const MEMBERS: Record<string, Member[]> = {
  A팀: [
    { id: "a1", name: "이민준", year: "21" },
    { id: "a2", name: "박서연", year: "22" },
    { id: "a3", name: "김도현", year: "21" },
    { id: "a4", name: "최지우", year: "23" },
    { id: "a5", name: "정하은", year: "22" },
    { id: "a6", name: "오승현", year: "21" },
    { id: "a7", name: "한예린", year: "23" },
    { id: "a8", name: "윤재혁", year: "22" },
  ],
  B팀: [
    { id: "b1", name: "강태양", year: "21" },
    { id: "b2", name: "임수진", year: "22" },
    { id: "b3", name: "류현우", year: "23" },
    { id: "b4", name: "신아름", year: "21" },
    { id: "b5", name: "백민혁", year: "22" },
    { id: "b6", name: "장나연", year: "23" },
    { id: "b7", name: "조영준", year: "21" },
    { id: "b8", name: "허채원", year: "22" },
  ],
  C팀: [
    { id: "c1", name: "문지훈", year: "21" },
    { id: "c2", name: "노유진", year: "22" },
    { id: "c3", name: "원승민", year: "23" },
    { id: "c4", name: "송하늘", year: "22" },
    { id: "c5", name: "양도연", year: "21" },
    { id: "c6", name: "진서영", year: "23" },
    { id: "c7", name: "표건우", year: "22" },
    { id: "c8", name: "홍미래", year: "21" },
  ],
  D팀: [
    { id: "d1", name: "고준서", year: "22" },
    { id: "d2", name: "남소희", year: "23" },
    { id: "d3", name: "도현진", year: "21" },
    { id: "d4", name: "마지원", year: "22" },
    { id: "d5", name: "배수현", year: "23" },
    { id: "d6", name: "서태준", year: "21" },
    { id: "d7", name: "안예은", year: "22" },
    { id: "d8", name: "차민규", year: "23" },
  ],
};
